/********************************************************************
* TableDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TableDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTableDict();
extern void G__cpp_setup_inheritanceTableDict();
extern void G__cpp_setup_typetableTableDict();
extern void G__cpp_setup_memvarTableDict();
extern void G__cpp_setup_globalTableDict();
extern void G__cpp_setup_memfuncTableDict();
extern void G__cpp_setup_funcTableDict();
extern void G__set_cpp_environmentTableDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "LIP/TauAnalysis/interface/Table.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TableDictLN_TClass;
extern G__linked_taginfo G__TableDictLN_TBuffer;
extern G__linked_taginfo G__TableDictLN_TMemberInspector;
extern G__linked_taginfo G__TableDictLN_TObject;
extern G__linked_taginfo G__TableDictLN_TNamed;
extern G__linked_taginfo G__TableDictLN_TString;
extern G__linked_taginfo G__TableDictLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__TableDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__TableDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__TableDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__TableDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TableDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TableDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TableDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TableDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TableDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TableDictLN_TH1D;
extern G__linked_taginfo G__TableDictLN_Column;
extern G__linked_taginfo G__TableDictLN_Table;
extern G__linked_taginfo G__TableDictLN_vectorlEColumnmUcOallocatorlEColumnmUgRsPgR;
extern G__linked_taginfo G__TableDictLN_reverse_iteratorlEvectorlEColumnmUcOallocatorlEColumnmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TableDictLN_Column_speclEfloatgR;
extern G__linked_taginfo G__TableDictLN_Column_speclEshortgR;
extern G__linked_taginfo G__TableDictLN_Column_speclEdoublegR;
extern G__linked_taginfo G__TableDictLN_Column_speclEunsignedsPshortgR;
extern G__linked_taginfo G__TableDictLN_Column_speclEconstsPcharmUgR;
extern G__linked_taginfo G__TableDictLN_vectorlEconstsPcharmUcOallocatorlEconstsPcharmUgRsPgR;
extern G__linked_taginfo G__TableDictLN_reverse_iteratorlEvectorlEconstsPcharmUcOallocatorlEconstsPcharmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TableDictLN_Column_speclETStringgR;
extern G__linked_taginfo G__TableDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__TableDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef Column_spec<float> G__Column_speclEfloatgR;
typedef Column_spec<short> G__Column_speclEshortgR;
typedef Column_spec<double> G__Column_speclEdoublegR;
typedef Column_spec<unsigned short> G__Column_speclEunsignedsPshortgR;
typedef Column_spec<const char*> G__Column_speclEconstsPcharmUgR;
typedef Column_spec<TString> G__Column_speclETStringgR;
