//
// File generated by rootcint at Fri Dec 19 16:20:36 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME rootdoubleDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "LIP/TauAnalysis/interface/rootdoubleDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void rootdouble_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_rootdouble(void *p = 0);
   static void *newArray_rootdouble(Long_t size, void *p);
   static void delete_rootdouble(void *p);
   static void deleteArray_rootdouble(void *p);
   static void destruct_rootdouble(void *p);
   static void streamer_rootdouble(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::rootdouble*)
   {
      ::rootdouble *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::rootdouble >(0);
      static ::ROOT::TGenericClassInfo 
         instance("rootdouble", ::rootdouble::Class_Version(), "./interface/rootdouble.h", 6,
                  typeid(::rootdouble), DefineBehavior(ptr, ptr),
                  &::rootdouble::Dictionary, isa_proxy, 0,
                  sizeof(::rootdouble) );
      instance.SetNew(&new_rootdouble);
      instance.SetNewArray(&newArray_rootdouble);
      instance.SetDelete(&delete_rootdouble);
      instance.SetDeleteArray(&deleteArray_rootdouble);
      instance.SetDestructor(&destruct_rootdouble);
      instance.SetStreamerFunc(&streamer_rootdouble);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::rootdouble*)
   {
      return GenerateInitInstanceLocal((::rootdouble*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::rootdouble*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *rootdouble::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *rootdouble::Class_Name()
{
   return "rootdouble";
}

//______________________________________________________________________________
const char *rootdouble::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::rootdouble*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int rootdouble::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::rootdouble*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void rootdouble::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::rootdouble*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *rootdouble::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::rootdouble*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void rootdouble::Streamer(TBuffer &R__b)
{
   // Stream an object of class rootdouble.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TNamed::Streamer(R__b);
      R__b >> information;
      R__b.CheckByteCount(R__s, R__c, rootdouble::IsA());
   } else {
      R__c = R__b.WriteVersion(rootdouble::IsA(), kTRUE);
      TNamed::Streamer(R__b);
      R__b << information;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void rootdouble::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class rootdouble.
      TClass *R__cl = ::rootdouble::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "information", &information);
      TNamed::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_rootdouble(void *p) {
      return  p ? new(p) ::rootdouble : new ::rootdouble;
   }
   static void *newArray_rootdouble(Long_t nElements, void *p) {
      return p ? new(p) ::rootdouble[nElements] : new ::rootdouble[nElements];
   }
   // Wrapper around operator delete
   static void delete_rootdouble(void *p) {
      delete ((::rootdouble*)p);
   }
   static void deleteArray_rootdouble(void *p) {
      delete [] ((::rootdouble*)p);
   }
   static void destruct_rootdouble(void *p) {
      typedef ::rootdouble current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_rootdouble(TBuffer &buf, void *obj) {
      ((::rootdouble*)obj)->::rootdouble::Streamer(buf);
   }
} // end of namespace ROOT for class ::rootdouble

/********************************************************
* rootdoubleDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablerootdoubleDict();

extern "C" void G__set_cpp_environmentrootdoubleDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("interface/rootdouble.h");
  G__cpp_reset_tagtablerootdoubleDict();
}
#include <new>
extern "C" int G__cpp_dllrevrootdoubleDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* rootdouble */
static int G__rootdoubleDict_177_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   rootdouble* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new rootdouble[n];
     } else {
       p = new((void*) gvp) rootdouble[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new rootdouble;
     } else {
       p = new((void*) gvp) rootdouble;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__rootdoubleDictLN_rootdouble));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdoubleDict_177_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   rootdouble* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 2
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new rootdouble((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
   } else {
     p = new((void*) gvp) rootdouble((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__rootdoubleDictLN_rootdouble));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdoubleDict_177_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const rootdouble*) G__getstructoffset())->GetInformation());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdoubleDict_177_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((rootdouble*) G__getstructoffset())->SetInformation((const double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdoubleDict_177_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) rootdouble::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdoubleDict_177_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) rootdouble::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdoubleDict_177_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) rootdouble::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdoubleDict_177_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      rootdouble::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdoubleDict_177_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((rootdouble*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdoubleDict_177_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) rootdouble::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdoubleDict_177_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) rootdouble::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdoubleDict_177_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) rootdouble::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdoubleDict_177_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) rootdouble::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__rootdoubleDict_177_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   rootdouble* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new rootdouble(*(rootdouble*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__rootdoubleDictLN_rootdouble));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef rootdouble G__Trootdouble;
static int G__rootdoubleDict_177_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (rootdouble*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((rootdouble*) (soff+(sizeof(rootdouble)*i)))->~G__Trootdouble();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (rootdouble*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((rootdouble*) (soff))->~G__Trootdouble();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__rootdoubleDict_177_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   rootdouble* dest = (rootdouble*) G__getstructoffset();
   *dest = *(rootdouble*) libp->para[0].ref;
   const rootdouble& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* rootdouble */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncrootdoubleDict {
 public:
  G__Sizep2memfuncrootdoubleDict(): p(&G__Sizep2memfuncrootdoubleDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncrootdoubleDict::*p)();
};

size_t G__get_sizep2memfuncrootdoubleDict()
{
  G__Sizep2memfuncrootdoubleDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancerootdoubleDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__rootdoubleDictLN_rootdouble))) {
     rootdouble *G__Lderived;
     G__Lderived=(rootdouble*)0x1000;
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rootdoubleDictLN_rootdouble),G__get_linked_tagnum(&G__rootdoubleDictLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rootdoubleDictLN_rootdouble),G__get_linked_tagnum(&G__rootdoubleDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablerootdoubleDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__rootdoubleDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__rootdoubleDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rootdoubleDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__rootdoubleDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rootdoubleDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__rootdoubleDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__rootdoubleDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rootdoubleDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__rootdoubleDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rootdoubleDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* rootdouble */
static void G__setup_memvarrootdouble(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__rootdoubleDictLN_rootdouble));
   { rootdouble *p; p=(rootdouble*)0x1000; if (p) { }
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"information=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rootdoubleDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarrootdoubleDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncrootdouble(void) {
   /* rootdouble */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__rootdoubleDictLN_rootdouble));
   G__memfunc_setup("rootdouble",1087,G__rootdoubleDict_177_0_1, 105, G__get_linked_tagnum(&G__rootdoubleDictLN_rootdouble), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("rootdouble",1087,G__rootdoubleDict_177_0_2, 105, G__get_linked_tagnum(&G__rootdoubleDictLN_rootdouble), -1, 0, 2, 1, 1, 0, 
"C - - 10 - name C - - 10 - title", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetInformation",1446,G__rootdoubleDict_177_0_3, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetInformation",1458,G__rootdoubleDict_177_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 10 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__rootdoubleDict_177_0_5, 85, G__get_linked_tagnum(&G__rootdoubleDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&rootdouble::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__rootdoubleDict_177_0_6, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&rootdouble::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__rootdoubleDict_177_0_7, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&rootdouble::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__rootdoubleDict_177_0_8, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&rootdouble::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__rootdoubleDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__rootdoubleDict_177_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__rootdoubleDict_177_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&rootdouble::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__rootdoubleDict_177_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&rootdouble::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__rootdoubleDict_177_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&rootdouble::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__rootdoubleDict_177_0_16, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&rootdouble::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("rootdouble", 1087, G__rootdoubleDict_177_0_17, (int) ('i'), G__get_linked_tagnum(&G__rootdoubleDictLN_rootdouble), -1, 0, 1, 1, 1, 0, "u 'rootdouble' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~rootdouble", 1213, G__rootdoubleDict_177_0_18, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__rootdoubleDict_177_0_19, (int) ('u'), G__get_linked_tagnum(&G__rootdoubleDictLN_rootdouble), -1, 1, 1, 1, 1, 0, "u 'rootdouble' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncrootdoubleDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalrootdoubleDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcrootdoubleDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__rootdoubleDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__rootdoubleDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__rootdoubleDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__rootdoubleDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__rootdoubleDictLN_TNamed = { "TNamed" , 99 , -1 };
G__linked_taginfo G__rootdoubleDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__rootdoubleDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__rootdoubleDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__rootdoubleDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__rootdoubleDictLN_rootdouble = { "rootdouble" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablerootdoubleDict() {
  G__rootdoubleDictLN_TClass.tagnum = -1 ;
  G__rootdoubleDictLN_TBuffer.tagnum = -1 ;
  G__rootdoubleDictLN_TMemberInspector.tagnum = -1 ;
  G__rootdoubleDictLN_TObject.tagnum = -1 ;
  G__rootdoubleDictLN_TNamed.tagnum = -1 ;
  G__rootdoubleDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__rootdoubleDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__rootdoubleDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__rootdoubleDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__rootdoubleDictLN_rootdouble.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablerootdoubleDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__rootdoubleDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__rootdoubleDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__rootdoubleDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__rootdoubleDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__rootdoubleDictLN_TNamed);
   G__get_linked_tagnum_fwd(&G__rootdoubleDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__rootdoubleDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__rootdoubleDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__rootdoubleDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__rootdoubleDictLN_rootdouble),sizeof(rootdouble),-1,62720,(char*)NULL,G__setup_memvarrootdouble,G__setup_memfuncrootdouble);
}
extern "C" void G__cpp_setuprootdoubleDict(void) {
  G__check_setup_version(30051515,"G__cpp_setuprootdoubleDict()");
  G__set_cpp_environmentrootdoubleDict();
  G__cpp_setup_tagtablerootdoubleDict();

  G__cpp_setup_inheritancerootdoubleDict();

  G__cpp_setup_typetablerootdoubleDict();

  G__cpp_setup_memvarrootdoubleDict();

  G__cpp_setup_memfuncrootdoubleDict();
  G__cpp_setup_globalrootdoubleDict();
  G__cpp_setup_funcrootdoubleDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncrootdoubleDict();
  return;
}
class G__cpp_setup_initrootdoubleDict {
  public:
    G__cpp_setup_initrootdoubleDict() { G__add_setup_func("rootdoubleDict",(G__incsetup)(&G__cpp_setuprootdoubleDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initrootdoubleDict() { G__remove_setup_func("rootdoubleDict"); }
};
G__cpp_setup_initrootdoubleDict G__cpp_setup_initializerrootdoubleDict;

